#!/usr/bin/env python3
"""Texel-style tuner for Boa's UCI eval scale knobs.

The tuner consumes CSV rows from tools/restriction_signal.mjs and optimizes
integer UCI scale values against game result labels. It intentionally operates
on exposed eval components first; per-constant table tuning can build on this
same data path after the component-scale baseline is established.
"""

from __future__ import annotations

import argparse
import csv
import math
from dataclasses import dataclass


DEFAULT_FEATURES = [
    "material_cp",
    "pst_cp",
    "mobility_cp",
    "pawn_structure_cp",
    "king_safety_cp",
    "trade_down_cp",
]

DEFAULT_ZERO_FEATURES = [
]

UCI_OPTION_BY_FEATURE = {
    "material_cp": "Eval Material Scale",
    "pst_cp": "Eval PST Scale",
    "mobility_cp": "Eval Mobility Scale",
    "pawn_structure_cp": "Eval Pawn Structure Scale",
    "king_safety_cp": "Eval King Safety Scale",
    "freedom_cp": "Eval Freedom Scale",
    "trade_down_cp": "Eval Trade Down Scale",
    "weak_squares_cp": "Eval Weak Squares Scale",
    "coordination_cp": "Eval Coordination Scale",
    "advanced_pawns_cp": "Eval Advanced Pawns Scale",
}


@dataclass
class Dataset:
    features: list[str]
    rows: list[list[float]]
    labels: list[float]


@dataclass
class TuneResult:
    scales: list[int]
    train_mse: float
    validation_mse: float | None
    accepted: bool


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "csv_path",
        nargs="?",
        default="analysis/restriction_signal/gm_quiet_features.csv",
        help="Quiet feature CSV generated by tools/restriction_signal.mjs",
    )
    parser.add_argument(
        "--features",
        default=",".join(DEFAULT_FEATURES),
        help="Comma-separated *_cp feature columns to tune.",
    )
    parser.add_argument(
        "--zero-features",
        default=",".join(DEFAULT_ZERO_FEATURES),
        help="Comma-separated *_cp feature columns to force to scale 0 in recommendations.",
    )
    parser.add_argument("--limit", type=int, default=0, help="Maximum rows to read. Default: all.")
    parser.add_argument("--k", type=float, default=0.004, help="Sigmoid slope. Default: 0.004.")
    parser.add_argument(
        "--steps",
        default="50,25,10,5,2,1",
        help="Coordinate descent step sizes. Default: 50,25,10,5,2,1.",
    )
    parser.add_argument("--min-scale", type=int, default=0)
    parser.add_argument("--max-scale", type=int, default=300)
    parser.add_argument(
        "--max-delta",
        type=int,
        default=300,
        help="Maximum scale movement from --initial-scale. Default: unconstrained.",
    )
    parser.add_argument(
        "--l2",
        type=float,
        default=0.0,
        help="L2 penalty per squared scale point away from --initial-scale.",
    )
    parser.add_argument(
        "--validation-fraction",
        type=float,
        default=0.2,
        help="Fraction of rows reserved for deterministic validation. Default: 0.2.",
    )
    parser.add_argument(
        "--no-validation-gate",
        action="store_true",
        help="Allow printing tuned scales even if holdout MSE does not improve.",
    )
    parser.add_argument(
        "--initial-scale",
        type=int,
        default=100,
        help="Initial scale for tuned features. Default: 100.",
    )
    return parser.parse_args()


def split_csv_arg(value: str) -> list[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


def label_from_result(value: str) -> float | None:
    if value == "":
        return None
    try:
        score = float(value)
    except ValueError:
        return None
    if score > 0:
        return 1.0
    if score < 0:
        return 0.0
    return 0.5


def number(row: dict[str, str], key: str) -> float | None:
    value = row.get(key, "")
    if value == "":
        return None
    try:
        parsed = float(value)
    except ValueError:
        return None
    if not math.isfinite(parsed):
        return None
    return parsed


def read_dataset(path: str, features: list[str], limit: int) -> Dataset:
    rows: list[list[float]] = []
    labels: list[float] = []
    with open(path, newline="", encoding="utf8") as handle:
        reader = csv.DictReader(handle)
        missing = [feature for feature in features if feature not in (reader.fieldnames or [])]
        if missing:
            raise SystemExit(f"Missing feature columns: {', '.join(missing)}")
        if "result_score" not in (reader.fieldnames or []):
            raise SystemExit("Missing required result_score column.")

        for row in reader:
            label = label_from_result(row.get("result_score", ""))
            values = [number(row, feature) for feature in features]
            if label is None or any(value is None for value in values):
                continue
            rows.append([float(value) for value in values if value is not None])
            labels.append(label)
            if limit > 0 and len(rows) >= limit:
                break

    if not rows:
        raise SystemExit("No usable rows found.")
    return Dataset(features=features, rows=rows, labels=labels)


def split_dataset(dataset: Dataset, validation_fraction: float) -> tuple[Dataset, Dataset | None]:
    if validation_fraction <= 0.0:
        return dataset, None
    if validation_fraction >= 0.5:
        raise SystemExit("--validation-fraction must be less than 0.5")

    validation_every = max(2, round(1.0 / validation_fraction))
    train_rows: list[list[float]] = []
    train_labels: list[float] = []
    validation_rows: list[list[float]] = []
    validation_labels: list[float] = []

    for index, (row, label) in enumerate(zip(dataset.rows, dataset.labels)):
        if index % validation_every == 0:
            validation_rows.append(row)
            validation_labels.append(label)
            continue
        train_rows.append(row)
        train_labels.append(label)

    if not train_rows or not validation_rows:
        raise SystemExit("Validation split produced an empty train or validation set.")

    return (
        Dataset(features=dataset.features, rows=train_rows, labels=train_labels),
        Dataset(features=dataset.features, rows=validation_rows, labels=validation_labels),
    )


def sigmoid(k: float, cp: float) -> float:
    x = max(-60.0, min(60.0, k * cp))
    return 1.0 / (1.0 + math.exp(-x))


def mse(labels: list[float], evals: list[float], k: float) -> float:
    total = 0.0
    for label, cp in zip(labels, evals):
        estimate = sigmoid(k, cp)
        diff = estimate - label
        total += diff * diff
    return total / len(labels)


def initial_evals(dataset: Dataset, scales: list[int]) -> list[float]:
    return [
        sum(value * scale / 100.0 for value, scale in zip(row, scales))
        for row in dataset.rows
    ]


def shifted_evals(dataset: Dataset, evals: list[float], index: int, delta_scale: int) -> list[float]:
    factor = delta_scale / 100.0
    return [cp + row[index] * factor for cp, row in zip(evals, dataset.rows)]


def objective(labels: list[float], evals: list[float], scales: list[int], args: argparse.Namespace) -> float:
    penalty = args.l2 * sum((scale - args.initial_scale) ** 2 for scale in scales)
    return mse(labels, evals, args.k) + penalty


def tune(
    train: Dataset,
    validation: Dataset | None,
    args: argparse.Namespace,
) -> TuneResult:
    steps = [int(step) for step in split_csv_arg(args.steps)]
    lower = max(args.min_scale, args.initial_scale - args.max_delta)
    upper = min(args.max_scale, args.initial_scale + args.max_delta)
    scales = [args.initial_scale for _ in train.features]
    evals = initial_evals(train, scales)
    best = objective(train.labels, evals, scales, args)

    for step in steps:
        improved = True
        while improved:
            improved = False
            for index, _feature in enumerate(train.features):
                current_scale = scales[index]
                best_candidate = (best, current_scale, evals)
                for direction in (1, -1):
                    candidate_scale = max(
                        lower,
                        min(upper, current_scale + direction * step),
                    )
                    if candidate_scale == current_scale:
                        continue
                    candidate_scales = scales.copy()
                    candidate_scales[index] = candidate_scale
                    candidate_evals = shifted_evals(
                        train, evals, index, candidate_scale - current_scale
                    )
                    candidate_error = objective(train.labels, candidate_evals, candidate_scales, args)
                    if candidate_error < best_candidate[0]:
                        best_candidate = (candidate_error, candidate_scale, candidate_evals)

                if best_candidate[1] != current_scale:
                    best, scales[index], evals = best_candidate
                    improved = True

    train_mse = mse(train.labels, evals, args.k)
    validation_mse = None
    accepted = True
    if validation is not None:
        initial_scales = [args.initial_scale for _ in validation.features]
        initial_validation_mse = mse(
            validation.labels,
            initial_evals(validation, initial_scales),
            args.k,
        )
        validation_mse = mse(validation.labels, initial_evals(validation, scales), args.k)
        accepted = validation_mse < initial_validation_mse or args.no_validation_gate
        if not accepted:
            scales = [args.initial_scale for _ in train.features]
            train_mse = mse(train.labels, initial_evals(train, scales), args.k)
            validation_mse = initial_validation_mse

    return TuneResult(scales=scales, train_mse=train_mse, validation_mse=validation_mse, accepted=accepted)


def print_recommendations(features: list[str], scales: list[int], zero_features: list[str]) -> None:
    print("\nRecommended UCI options:")
    for feature, scale in zip(features, scales):
        option = UCI_OPTION_BY_FEATURE.get(feature, feature)
        print(f"{option}={scale}")
    for feature in zero_features:
        option = UCI_OPTION_BY_FEATURE.get(feature, feature)
        print(f"{option}=0")


def main() -> None:
    args = parse_args()
    features = split_csv_arg(args.features)
    zero_features = split_csv_arg(args.zero_features)
    dataset = read_dataset(args.csv_path, features, args.limit)
    train, validation = split_dataset(dataset, args.validation_fraction)
    initial_scales = [args.initial_scale for _ in train.features]
    initial_train_mse = mse(train.labels, initial_evals(train, initial_scales), args.k)
    initial_validation_mse = None
    if validation is not None:
        initial_validation_mse = mse(
            validation.labels,
            initial_evals(validation, initial_scales),
            args.k,
        )
    result = tune(train, validation, args)

    print(f"rows={len(dataset.rows)}")
    print(f"train_rows={len(train.rows)}")
    if validation is not None:
        print(f"validation_rows={len(validation.rows)}")
    print(f"k={args.k}")
    print(f"l2={args.l2}")
    print(f"max_delta={args.max_delta}")
    print(f"validation_gate={not args.no_validation_gate}")
    print(f"accepted={result.accepted}")
    print(f"initial_train_mse={initial_train_mse:.8f}")
    print(f"best_train_mse={result.train_mse:.8f}")
    print(f"delta_train_mse={initial_train_mse - result.train_mse:.8f}")
    if initial_validation_mse is not None and result.validation_mse is not None:
        print(f"initial_validation_mse={initial_validation_mse:.8f}")
        print(f"best_validation_mse={result.validation_mse:.8f}")
        print(f"delta_validation_mse={initial_validation_mse - result.validation_mse:.8f}")
    print("\nTuned scales:")
    for feature, scale in zip(features, result.scales):
        print(f"{feature},{scale}")
    print_recommendations(features, result.scales, zero_features)


if __name__ == "__main__":
    main()
