#!/usr/bin/env python3
"""Texel-style tuner for Boa's UCI eval scale knobs.

The tuner consumes CSV rows from tools/restriction_signal.mjs and optimizes
integer UCI scale values against game result labels. It intentionally operates
on exposed eval components first; per-constant table tuning can build on this
same data path after the component-scale baseline is established.
"""

from __future__ import annotations

import argparse
import csv
import math
from dataclasses import dataclass


DEFAULT_FEATURES = [
    "material_cp",
    "pst_cp",
    "mobility_cp",
    "pawn_structure_cp",
    "king_safety_cp",
    "trade_down_cp",
]

DEFAULT_ZERO_FEATURES = [
    "freedom_cp",
    "weak_squares_cp",
    "coordination_cp",
    "advanced_pawns_cp",
]

UCI_OPTION_BY_FEATURE = {
    "material_cp": "Eval Material Scale",
    "pst_cp": "Eval PST Scale",
    "mobility_cp": "Eval Mobility Scale",
    "pawn_structure_cp": "Eval Pawn Structure Scale",
    "king_safety_cp": "Eval King Safety Scale",
    "freedom_cp": "Eval Freedom Scale",
    "trade_down_cp": "Eval Trade Down Scale",
    "weak_squares_cp": "Eval Weak Squares Scale",
    "coordination_cp": "Eval Coordination Scale",
    "advanced_pawns_cp": "Eval Advanced Pawns Scale",
}


@dataclass
class Dataset:
    features: list[str]
    rows: list[list[float]]
    labels: list[float]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "csv_path",
        nargs="?",
        default="analysis/restriction_signal/gm_quiet_features.csv",
        help="Quiet feature CSV generated by tools/restriction_signal.mjs",
    )
    parser.add_argument(
        "--features",
        default=",".join(DEFAULT_FEATURES),
        help="Comma-separated *_cp feature columns to tune.",
    )
    parser.add_argument(
        "--zero-features",
        default=",".join(DEFAULT_ZERO_FEATURES),
        help="Comma-separated *_cp feature columns to force to scale 0 in recommendations.",
    )
    parser.add_argument("--limit", type=int, default=0, help="Maximum rows to read. Default: all.")
    parser.add_argument("--k", type=float, default=0.004, help="Sigmoid slope. Default: 0.004.")
    parser.add_argument(
        "--steps",
        default="50,25,10,5,2,1",
        help="Coordinate descent step sizes. Default: 50,25,10,5,2,1.",
    )
    parser.add_argument("--min-scale", type=int, default=0)
    parser.add_argument("--max-scale", type=int, default=300)
    parser.add_argument(
        "--initial-scale",
        type=int,
        default=100,
        help="Initial scale for tuned features. Default: 100.",
    )
    return parser.parse_args()


def split_csv_arg(value: str) -> list[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


def label_from_result(value: str) -> float | None:
    if value == "":
        return None
    try:
        score = float(value)
    except ValueError:
        return None
    if score > 0:
        return 1.0
    if score < 0:
        return 0.0
    return 0.5


def number(row: dict[str, str], key: str) -> float | None:
    value = row.get(key, "")
    if value == "":
        return None
    try:
        parsed = float(value)
    except ValueError:
        return None
    if not math.isfinite(parsed):
        return None
    return parsed


def read_dataset(path: str, features: list[str], limit: int) -> Dataset:
    rows: list[list[float]] = []
    labels: list[float] = []
    with open(path, newline="", encoding="utf8") as handle:
        reader = csv.DictReader(handle)
        missing = [feature for feature in features if feature not in (reader.fieldnames or [])]
        if missing:
            raise SystemExit(f"Missing feature columns: {', '.join(missing)}")
        if "result_score" not in (reader.fieldnames or []):
            raise SystemExit("Missing required result_score column.")

        for row in reader:
            label = label_from_result(row.get("result_score", ""))
            values = [number(row, feature) for feature in features]
            if label is None or any(value is None for value in values):
                continue
            rows.append([float(value) for value in values if value is not None])
            labels.append(label)
            if limit > 0 and len(rows) >= limit:
                break

    if not rows:
        raise SystemExit("No usable rows found.")
    return Dataset(features=features, rows=rows, labels=labels)


def sigmoid(k: float, cp: float) -> float:
    x = max(-60.0, min(60.0, k * cp))
    return 1.0 / (1.0 + math.exp(-x))


def mse(labels: list[float], evals: list[float], k: float) -> float:
    total = 0.0
    for label, cp in zip(labels, evals):
        estimate = sigmoid(k, cp)
        diff = estimate - label
        total += diff * diff
    return total / len(labels)


def initial_evals(dataset: Dataset, scales: list[int]) -> list[float]:
    return [
        sum(value * scale / 100.0 for value, scale in zip(row, scales))
        for row in dataset.rows
    ]


def shifted_evals(dataset: Dataset, evals: list[float], index: int, delta_scale: int) -> list[float]:
    factor = delta_scale / 100.0
    return [cp + row[index] * factor for cp, row in zip(evals, dataset.rows)]


def tune(dataset: Dataset, args: argparse.Namespace) -> tuple[list[int], float]:
    steps = [int(step) for step in split_csv_arg(args.steps)]
    scales = [args.initial_scale for _ in dataset.features]
    evals = initial_evals(dataset, scales)
    best = mse(dataset.labels, evals, args.k)

    for step in steps:
        improved = True
        while improved:
            improved = False
            for index, _feature in enumerate(dataset.features):
                current_scale = scales[index]
                best_candidate = (best, current_scale, evals)
                for direction in (1, -1):
                    candidate_scale = max(
                        args.min_scale,
                        min(args.max_scale, current_scale + direction * step),
                    )
                    if candidate_scale == current_scale:
                        continue
                    candidate_evals = shifted_evals(
                        dataset, evals, index, candidate_scale - current_scale
                    )
                    candidate_error = mse(dataset.labels, candidate_evals, args.k)
                    if candidate_error < best_candidate[0]:
                        best_candidate = (candidate_error, candidate_scale, candidate_evals)

                if best_candidate[1] != current_scale:
                    best, scales[index], evals = best_candidate
                    improved = True
    return scales, best


def print_recommendations(features: list[str], scales: list[int], zero_features: list[str]) -> None:
    print("\nRecommended UCI options:")
    for feature, scale in zip(features, scales):
        option = UCI_OPTION_BY_FEATURE.get(feature, feature)
        print(f"{option}={scale}")
    for feature in zero_features:
        option = UCI_OPTION_BY_FEATURE.get(feature, feature)
        print(f"{option}=0")


def main() -> None:
    args = parse_args()
    features = split_csv_arg(args.features)
    zero_features = split_csv_arg(args.zero_features)
    dataset = read_dataset(args.csv_path, features, args.limit)
    initial_scales = [args.initial_scale for _ in dataset.features]
    initial_error = mse(dataset.labels, initial_evals(dataset, initial_scales), args.k)
    scales, best = tune(dataset, args)

    print(f"rows={len(dataset.rows)}")
    print(f"k={args.k}")
    print(f"initial_mse={initial_error:.8f}")
    print(f"best_mse={best:.8f}")
    print(f"delta_mse={initial_error - best:.8f}")
    print("\nTuned scales:")
    for feature, scale in zip(features, scales):
        print(f"{feature},{scale}")
    print_recommendations(features, scales, zero_features)


if __name__ == "__main__":
    main()
